schema: "classroom50/repo-config/v1"
classroom: "am-class"
assignment: "css-cv"
owner:
  username: "AdenRubenstein"
  id: 152738995
  accepted_at: "2026-09-01T21:12:50Z"
source:
  owner: "CSCI4300-Web-Programming"
  owner_id: 212650580
  repo: "css-cv-template"
  branch: "main"
